import json
import re

# Comprehensive phrase-level translations (order matters - longer phrases first)
PHRASE_MAP = [
    # Module titles
    ("PAISE KI BASIC SAMAJH FOUNDATION", "BASIC MONEY UNDERSTANDING FOUNDATION"),
    ("BUDGETING IN REAL LIFE PRACTICAL", "BUDGETING IN REAL LIFE PRACTICAL"),
    ("SAVING STRATEGIES SMART SAVING", "SAVING STRATEGIES SMART SAVING"),
    ("EMERGENCY FUND PROTECTION SHIELD", "EMERGENCY FUND PROTECTION SHIELD"),
    ("DEBT AUR CREDIT DANGER ZONE", "DEBT AND CREDIT DANGER ZONE"),
    ("BANKING BASICS EVERYDAY BANKING", "BANKING BASICS EVERYDAY BANKING"),
    ("INVESTMENT BASICS GROW YOUR MONEY", "INVESTMENT BASICS GROW YOUR MONEY"),
    ("FINANCIAL INDEPENDENCE FREEDOM", "FINANCIAL INDEPENDENCE FREEDOM"),
    ("INSURANCE BASICS PROTECTION", "INSURANCE BASICS PROTECTION"),
    ("REAL-WORLD FINANCIAL REAL-WORLD SCENARIOS", "REAL-WORLD FINANCIAL REAL-WORLD SCENARIOS"),

    # Topic titles
    ("Money Kya Hai", "What Is Money"),
    ("Income Kya Hai", "What Is Income"),
    ("Expense Kya Hai", "What Is Expense"),
    ("Saving Kya Hai", "What Is Saving"),
    ("Budget Kya Hai", "What Is Budget"),
    ("Financial Awareness", "Financial Awareness"),
    ("Student Budget Step-by-Step", "Student Budget Step-by-Step"),
    ("Expense Tracking", "Expense Tracking"),
    ("Needs vs Wants Deep Dive", "Needs vs Wants Deep Dive"),
    ("Common Budget Mistakes", "Common Budget Mistakes"),
    ("Ready-Made Budget Templates", "Ready-Made Budget Templates"),
    ("Irregular Income Budgeting", "Irregular Income Budgeting"),
    ("Kitna Save Karna Chahiye", "How Much Should You Save"),
    ("Saving Ke Barriers Aur Solutions", "Saving Barriers and Solutions"),
    ("Saving Techniques", "Saving Techniques"),
    ("Short-Term vs Medium-Term vs Long-Term Saving Goals", "Short-Term vs Medium-Term vs Long-Term Saving Goals"),
    ("Inflation Ka Asar", "The Impact of Inflation"),
    ("Power of Compounding", "Power of Compounding"),
    ("Student-Specific Saving Hacks", "Student-Specific Saving Tips"),
    ("Emergency Fund Kya Hai", "What Is an Emergency Fund"),
    ("Kitna Hona Chahiye", "How Much Should It Be"),
    ("Kaise Banayein", "How to Build It"),
    ("Kahan Rakhein", "Where to Keep It"),
    ("Kab Use Karein", "When to Use It"),
    ("Real-Life Stories", "Real-Life Stories"),
    ("Emergency Fund Wapas Kaise Bharein", "How to Replenish Your Emergency Fund"),
    ("Good Debt vs Bad Debt", "Good Debt vs Bad Debt"),
    ("Credit Card", "Credit Card"),
    ("Student Loans / Education Loans", "Student Loans / Education Loans"),
    ("Personal Loan vs FD Loan vs Family Loan", "Personal Loan vs FD Loan vs Family Loan"),
    ("Credit Score / CIBIL Score", "Credit Score / CIBIL Score"),
    ("Debt Trap", "Debt Trap"),
    ("Debt Se Kaise Nikle", "How to Get Out of Debt"),
    ("Types of Accounts", "Types of Accounts"),
    ("Fixed Deposit (FD)", "Fixed Deposit (FD)"),
    ("Recurring Deposit (RD)", "Recurring Deposit (RD)"),
    ("Digital Payments", "Digital Payments"),
    ("Cards Explained", "Cards Explained"),
    ("Hidden Bank Charges", "Hidden Bank Charges"),
    ("KYC and Online Safety", "KYC and Online Safety"),
    ("Investment Kya Hai", "What Is Investing"),
    ("Mutual Fund Complete Guide", "Mutual Fund Complete Guide"),
    ("FD vs RD vs SIP vs PPF", "FD vs RD vs SIP vs PPF"),
    ("PPF", "PPF"),
    ("Stock Market Basics", "Stock Market Basics"),
    ("Gold Investment", "Gold Investment"),
    ("Crypto", "Crypto"),
    ("Asset Allocation for Students", "Asset Allocation for Students"),
    ("Tax Basics for Students (Cross-reference Module 10) Quick overview:", "Tax Basics for Students (Cross-reference Module 10) Quick overview:"),
    ("Financial Independence Kya Hai", "What Is Financial Independence"),
    ("FIRE Movement", "FIRE Movement"),
    ("Passive Income Sources for Students", "Passive Income Sources for Students"),
    ("Side Hustle for Indian Students", "Side Hustle for Indian Students"),
    ("Retirement Planning for Students", "Retirement Planning for Students"),
    ("Financial Freedom Calculator", "Financial Freedom Calculator"),
    ("Real Indian Examples", "Real Indian Examples"),
    ("Rich Dad Poor Dad", "Rich Dad Poor Dad"),
    ("Psychology of Money", "Psychology of Money"),
    ("Insurance Kya Hai", "What Is Insurance"),
    ("Health Insurance", "Health Insurance"),
    ("Life Insurance", "Life Insurance"),
    ("Vehicle Insurance", "Vehicle Insurance"),
    ("Insurance Se Investment MAT Karo", "Do Not Mix Insurance with Investment"),
    ("10 Common Insurance Mistakes Indians Make", "10 Common Insurance Mistakes Indians Make"),
    ("Income Tax Kya Hai", "What Is Income Tax"),
    ("Important Tax Sections for Students", "Important Tax Sections for Students"),
    ("Form 16 Kya Hai", "What Is Form 16"),
    ("ITR Filing", "ITR Filing"),
    ("Student-Specific Tax Situations", "Student-Specific Tax Situations"),
    ("TDS Kya Hai", "What Is TDS"),
    ("Old Regime vs New Regime", "Old Regime vs New Regime"),
    ("Tax-Saving Investments Comparison", "Tax-Saving Investments Comparison"),
    ("Complete Financial Plans", "Complete Financial Plans"),
    ("\"What If\" Scenarios", "\"What If\" Scenarios"),
    ("Financial Checklist by Life Stage", "Financial Checklist by Life Stage"),
    ("Indian Middle Class Financial", "Indian Middle Class Financial"),
    ("Financial Red Flags in Relationships", "Financial Red Flags in Relationships"),
    ("Scams Targeting Students", "Scams Targeting Students"),
]

# Phrase-level Hinglish to English translations for content
CONTENT_PHRASES = [
    # Common sentence starters and patterns
    ("Jab hum \"paisa\" sunte hain", "When we hear the word \"money\""),
    ("toh dimaag mein turant notes aur coins ka khayal aata hai", "our mind immediately thinks of notes and coins"),
    ("Lekin bhai, paisa sirf paper ya metal nahi hai", "But money is not just paper or metal"),
    ("yeh ek concept hai", "it is a concept"),
    ("ek medium hai jiske through hum value ko exchange karte hain", "a medium through which we exchange value"),
    ("Socho, agar paisa na hota toh kya hota", "Imagine, what if money did not exist"),
    ("Agar tumhe chai chahiye aur tumhare paas sirf ek kitab hai", "If you want tea and you only have a book"),
    ("toh tum chaiwale ko kitab doge aur woh tumhe chai dega", "you give the book to the tea seller and he gives you tea"),
    ("yeh barter system hai", "this is the barter system"),
    ("Lekin kya chaiwale ko kitab chahiye", "But does the tea seller want the book"),
    ("Shayad nahi", "Probably not"),
    ("Yahi problem thi barter system mein", "This was the problem with the barter system"),
    ("\"double coincidence of wants\" kehte hain isko", "it is called the \"double coincidence of wants\""),
    ("Dono ko ek dusre ki cheez chahiye honi chahiye", "Both parties need to want what the other has"),
    ("Isi problem ko solve karne ke liye paisa bana", "Money was created to solve this very problem"),
    ("ek aisi cheez jo sabko accept karein", "something that everyone accepts"),
    ("jiski value fixed ho", "whose value is fixed"),
    ("aur jo easily exchange ho sake", "and that can be easily exchanged"),

    ("Barter se Modern Money tak ka safar", "The journey from barter to modern money"),
    ("Pehle zamaane mein log cheezon se cheezein badalte the", "In earlier times, people exchanged things for things"),
    ("gehu se kapde", "wheat for clothes"),
    ("doodh se chawal", "milk for rice"),
    ("Lekin yeh system bahut inefficient tha", "But this system was very inefficient"),
    ("Phir logon ne precious metals jaise gold aur silver ko money ki tarah use karna shuru kiya", "Then people started using precious metals like gold and silver as money"),
    ("Kyunki gold sab jagah accept hota tha", "Because gold was accepted everywhere"),
    ("easily divide hota tha", "could be easily divided"),
    ("aur store bhi ho sakta tha", "and could also be stored"),
    ("Phir governments ne paper currency introduce ki", "Then governments introduced paper currency"),
    ("jo gold ke against issue hoti thi", "which was issued against gold"),
    ("Aaj ki date mein paisa \"fiat currency\" hai", "Today, money is \"fiat currency\""),
    ("government ne declare kiya hai ki yeh legal tender hai", "the government has declared it as legal tender"),
    ("bina kisi gold backing ke", "without any gold backing"),
    ("Iska matlab paisa ki value government ke trust pe based hai", "This means the value of money is based on trust in the government"),

    ("Digital Money ka Evolution", "Evolution of Digital Money"),
    ("Aaj ke daur mein paisa sirf cash nahi hai", "In today's world, money is not just cash"),
    ("Digital money", "Digital money"),
    ("UPI, wallets, bank transfers", "UPI, wallets, bank transfers"),
    ("yeh sab bhi paisa hai", "all of this is also money"),
    ("Tumne Google Pay se", "Did you pay via Google Pay"),
    ("chai ka payment kiya", "for tea"),
    ("Yeh bhi paisa hai", "This is also money"),
    ("bas physical form mein nahi hai", "it is just not in physical form"),

    # Common patterns for all modules
    ("ka simple matlab hai", "simply means"),
    ("ka matlab hai", "means"),
    ("ka matlab hai ki", "means that"),
    ("tumhare paas aane wala paisa", "the money coming to you"),
    ("tumhara jaane wala paisa", "the money going out from you"),
    ("Jo bhi source se paisa aata hai, woh income hai", "Whatever the source, money coming in is income"),
    ("Jo bhi paisa nikalta hai, woh expense hai", "Whatever money goes out is an expense"),
    ("aaj kam kharcha karo, kal ke liye paise rakhna", "spend less today, save money for tomorrow"),
    ("\"pehle spend karo, jo bacha woh save\"", "\"spend first, save whatever is left\""),
    ("Yeh approach kaam nahi karti", "This approach does not work"),
    ("kyunki usually kuch nahi bachta", "because usually nothing is left"),
    ("Correct approach hai \"Pay Yourself First\"", "The correct approach is \"Pay Yourself First\""),
    ("income aaya, pehle saving mein daalo", "when income comes, put it into savings first"),
    ("baaki se expenses chalao", "run your expenses with the rest"),

    # Module 2
    ("Karo", "Do"),
    ("karo", "do"),
    ("mat karo", "do not"),
    ("kaise", "how"),
    ("kahan", "where"),
    ("kyun", "why"),
    ("kya", "what"),
    ("kaunsa", "which"),
    ("kitna", "how much"),
    ("kab", "when"),
    ("Pehle", "First"),
    ("exact pata karo", "find out exactly"),
    ("tumhare paas kitna paisa aata hai", "how much money you receive"),
    ("Jo har mahine same rehta hai", "What remains the same every month"),
    ("Jo mahine pe depend karta hai", "What depends on the month"),
    ("Har Sunday 15 minute budget check karo", "Check your budget for 15 minutes every Sunday"),
    ("Kahan zyada ho gaya", "Where did you overspend"),
    ("Next month adjust karo", "Adjust next month"),
    ("Budget living document hai", "A budget is a living document"),
    ("rigid nahi", "not rigid"),
    ("flexible hona chahiye", "should be flexible"),

    # Saving module
    ("Yeh sabse common sawaal hai", "This is the most common question"),
    ("Answer depends hai tumhari income aur goals pe", "The answer depends on your income and goals"),
    ("lekin kuch general rules hain", "but there are some general rules"),
    ("Minimum 20% income save karo", "Save a minimum of 20% of your income"),
    ("Har income level pe applicable", "Applicable at every income level"),
    ("Aggressive savers 30-50% save karte hain", "Aggressive savers save 30-50%"),
    ("Agar expenses kam hain", "If expenses are low"),
    ("ghar pe rehte ho", "you live at home"),
    ("toh 50% possible hai", "then 50% is possible"),
    ("FIRE followers 50-70% bhi save karte hain", "FIRE followers save even 50-70%"),
    ("Financial independence early chahiye toh yeh karna padta hai", "If you want financial independence early, this is what it takes"),

    # Emergency fund
    ("SIRF emergency mein use hone hain", "are to be used ONLY in emergencies"),
    ("kisi bhi aur purpose ke liye nahi", "not for any other purpose"),
    ("Yeh tumhara financial safety net hai", "This is your financial safety net"),
    ("tumhari insurance hai bina koi premium ke", "your insurance without any premium"),
    ("Regular saving se yeh different hai", "This is different from regular saving"),
    ("regular saving goals ke liye hoti hai", "regular saving is for goals"),
    ("emergency fund sirf unexpected situations ke liye hai", "an emergency fund is only for unexpected situations"),
    ("Yeh accessible hona chahiye", "It should be accessible"),
    ("emergency mein 2-3 din mein cash available", "cash available within 2-3 days in an emergency"),

    # Debt
    ("Sab debt bure nahi hote", "Not all debt is bad"),
    ("Kuch debt tumhe aage le jaate hain", "Some debt takes you forward"),
    ("kuch peeche kheenchte hain", "some pulls you back"),
    ("Simple rule", "Simple rule"),
    ("Agar loan se asset ban raha hai = good debt", "If a loan is building an asset = good debt"),
    ("agar consumption hai = bad debt", "if it is for consumption = bad debt"),
    ("Asset woh cheez hai jo value badhati hai ya income generate karti hai", "An asset is something that increases in value or generates income"),
    ("Consumption woh cheez hai jo khatam ho jaati hai bina koi value", "Consumption is something that is used up without any value"),

    # Banking
    ("Bank account tumhari financial life ka base hai", "A bank account is the foundation of your financial life"),
    ("Bina bank account ke", "Without a bank account"),
    ("salary nahi aayegi", "salary will not come"),
    ("online payment nahi hoga", "online payments will not work"),
    ("saving safe nahi rahegi", "savings will not be safe"),
    ("Students ke liye sabse important account savings account hai", "For students, the most important account is the savings account"),

    # Investment
    ("Saving = paisa protect karna", "Saving = protecting money"),
    ("Investment = paisa grow karna", "Investing = growing money"),
    ("Yeh basic farq hai", "This is the basic difference"),
    ("Jab tum saving account mein paisa rakhte ho", "When you keep money in a savings account"),
    ("woh 3-4% grow hota hai", "it grows at 3-4%"),
    ("lekin inflation 5-6% hai", "but inflation is 5-6%"),
    ("toh real mein tumhara paisa kam ho raha hai", "so in real terms your money is decreasing"),
    ("Investment se tum inflation ko beat karte ho", "With investing, you beat inflation"),
    ("aur wealth create karte ho", "and create wealth"),
    ("\"Paise ko kaam pe lagao\"", "\"Put your money to work\""),
    ("tum kaam mat karo paise ke liye", "instead of working for money"),
    ("yeh investing ka core philosophy", "this is the core philosophy of investing"),

    # Insurance
    ("Insurance ek aisa system hai jismein aap chhota sa amount regularly dete hain", "Insurance is a system where you pay a small amount regularly"),
    ("aur bad mein koi badi emergency aaye toh insurance company bills bharti hai", "and if a big emergency comes later, the insurance company pays the bills"),
    ("Socho isko ek \"samuhik bachat\" jaisa", "Think of it like a \"collective savings\""),
    ("sab log thoda thoda paisa jodte hain", "everyone pools in a little money"),
    ("aur jiski emergency aati hai usko bada amount milta hai", "and whoever faces an emergency gets a large amount"),
    ("Yeh risk transfer ka concept hai", "This is the concept of risk transfer"),
    ("aapka risk insurance company le leti hai", "the insurance company takes on your risk"),
    ("chhote premium ke badle mein", "in exchange for a small premium"),
    ("Bina insurance ke", "Without insurance"),
    ("ek medical emergency ya accident aapke saare savings", "a medical emergency or accident [can wipe out] all your savings"),

    # Tax
    ("Income tax woh paisa hai jo aapki aamdani se sarkar kat ti hai", "Income tax is the money the government deducts from your earnings"),
    ("Yeh desh chalane ke liye chanda hai", "This is the contribution to run the country"),
    ("sadke, hospital, school, defense sab isse chalte hain", "roads, hospitals, schools, defense - all run on this"),
    ("India mein income tax direct tax hai", "In India, income tax is a direct tax"),
    ("matlab seedha aapki aamdani se cut hota hai", "meaning it is directly cut from your earnings"),
    ("Har financial year", "Every financial year"),
    ("aapki total income calculate hoti hai", "your total income is calculated"),
    ("aur uspe tax lagta hai", "and tax is applied on it"),
    ("based on \"slabs\"", "based on \"slabs\""),
    ("jyada income = jyada tax", "higher income = higher tax"),

    # FIRE
    ("Financial independence ka matlab hai", "Financial independence means"),
    ("tumhari saari expenses tumhari passive income se cover ho rahi hain", "all your expenses are covered by your passive income"),
    ("kaam karne ki zaroorat nahi", "you do not need to work"),
    ("\"Kaam karna\" aur \"kaam karna padta hai\" mein bahut farq hai", "There is a big difference between \"working\" and \"having to work\""),
    ("Financial independence ke baad tum kaam isliye karte ho", "After financial independence, you work because"),
    ("kyunki karna chahte ho", "you want to"),
    ("na ki karna padta hai", "not because you have to"),
    ("Yeh freedom ki feeling hai", "This is the feeling of freedom"),
    ("jo har student ko experience karni chahiye", "that every student should experience"),

    # Psychology of Money
    ("Paise ka logic nahi, psychology hai", "Money is not about logic, it is about psychology"),
    ("Log financially galat decisions lete hain", "People make wrong financial decisions"),
    ("kyunki unka emotional experience alag hota hai", "because their emotional experience is different"),
    ("Jo aapke liye bewakoofi lagta hai", "What seems foolish to you"),
    ("dusre ke liye perfectly logical ho sakta hai", "may be perfectly logical to someone else"),
    ("kyunki unki life story alag hai", "because their life story is different"),
    ("Isliye kisi ki financial choice judge mat karo", "So do not judge anyone's financial choices"),
    ("samjho", "understand them"),

    # Common Hindi words in context
    ("ke liye", "for"),
    ("ke saath", "with"),
    ("ke baad", "after"),
    ("se pehle", "before"),
    ("ke baare mein", "about"),
    ("ki wajah se", "because of"),
    ("ke through", "through"),
    ("ke alawa", "apart from"),
    ("ke bina", "without"),
    ("ke sath", "with"),
    ("mein", "in"),
    ("pe", "on"),
    ("se", "from"),
    ("tak", "up to"),
    ("lekin", "but"),
    ("aur", "and"),
    ("ya", "or"),
    ("kyunki", "because"),
    ("isliye", "therefore"),
    ("jab", "when"),
    ("tab", "then"),
    ("agar", "if"),
    ("toh", "then"),
    ("bhi", "also"),
    ("sirf", "only"),
    ("bahut", "very"),
    ("zyada", "more"),
    ("kam", "less"),
    ("accha", "good"),
    ("bura", "bad"),
    ("sahi", "right"),
    ("galat", "wrong"),
    ("zaroori", "necessary"),
    ("zaroorat", "need"),
    ("zaroori hai", "is necessary"),
    ("hota hai", "happens"),
    ("hoti hai", "happens"),
    ("hain", "are"),
    ("hai", "is"),
    ("nahi hai", "is not"),
    ("nahi hain", "are not"),
    ("ho jaata hai", "becomes"),
    ("ho jaati hai", "becomes"),
    ("karna padta hai", "have to do"),
    ("karna chahiye", "should do"),
    ("karna hai", "need to do"),
    ("kar sakte ho", "can do"),
    ("kar sakte hain", "can do"),
    ("mat karo", "do not"),
    ("shuru karo", "start"),
    ("band karo", "stop"),
    ("chalu rakho", "keep going"),
    ("save karo", "save"),
    ("spend karo", "spend"),
    ("invest karo", "invest"),
    ("check karo", "check"),
    ("dekh lo", "see for yourself"),
    ("yaad rakho", "remember"),
    ("dhyan do", "pay attention"),
    ("samjho", "understand"),
    ("padho", "read"),
    ("likho", "write"),
    ("banao", "make"),
    ("kholo", "open"),
    ("band mat karo", "do not close"),
    ("maintain karo", "maintain"),
    ("follow karo", "follow"),
    ("ignore mat karo", "do not ignore"),
    ("compare karo", "compare"),
    ("calculate karo", "calculate"),
    ("analyze karo", "analyze"),
    ("track karo", "track"),
    ("review karo", "review"),
    ("adjust karo", "adjust"),
    ("plan karo", "plan"),
    ("share karo", "share"),
    ("avoid karo", "avoid"),
    ("use karo", "use"),
    ("prefer karo", "prefer"),
    ("choose karo", "choose"),
    ("select karo", "select"),
    ("apply karo", "apply"),
    ("submit karo", "submit"),
    ("verify karo", "verify"),
    ("confirm karo", "confirm"),
    ("check karna", "checking"),
    ("padhna", "reading"),
    ("seekhna", "learning"),
    ("samajhna", "understanding"),
    ("karna", "doing"),
    ("shuru karna", "starting"),
    ("save karna", "saving"),
    ("spend karna", "spending"),
    ("invest karna", "investing"),
    ("banane mein", "in making"),
    ("karne mein", "in doing"),
    ("rahne mein", "in living"),
    ("kharcha", "expense"),
    ("kharche", "expenses"),
    ("bachat", "savings"),
    ("bacha hua", "remaining"),
    ("bacha", "left"),
    ("aamdani", "income"),
    ("kamai", "earnings"),
    ("maal", "goods"),
    ("cheez", "thing"),
    ("cheezein", "things"),
    ("paisa", "money"),
    ("paise", "money"),
    ("rupya", "rupee"),
    ("rupaye", "rupees"),
    ("mahine", "month/months"),
    ("mahina", "month"),
    ("saal", "year/years"),
    ("din", "day/days"),
    ("hafta", "week"),
    ("hafte", "weeks"),
    ("ghanta", "hour"),
    ("ghante", "hours"),
    ("minute", "minute"),
    ("peon", "rupees"),
    ("hazaar", "thousand"),
    ("lakh", "lakh"),
    ("crore", "crore"),
    ("chhota", "small"),
    ("bada", "big"),
    ("lamba", "long"),
    ("chota", "small"),
    ("naya", "new"),
    ("purana", "old"),
    ("accha", "good"),
    ("bura", "bad"),
    ("sundar", "beautiful"),
    ("zaroorat", "need"),
    ("mushkil", "difficult"),
    ("aasan", "easy"),
    ("important", "important"),
    ("useful", "useful"),
    ("free", "free"),
    ("safe", "safe"),
    ("best", "best"),
    ("worst", "worst"),
    ("smart", "smart"),
    ("simple", "simple"),
    ("clear", "clear"),
    ("real", "real"),
    ("actual", "actual"),
    ("fake", "fake"),
    ("scam", "scam"),
    ("fraud", "fraud"),
    ("risk", "risk"),
    ("profit", "profit"),
    ("loss", "loss"),
    ("return", "return"),
    ("returns", "returns"),
    ("growth", "growth"),
    ("wealth", "wealth"),
    ("income", "income"),
    ("expense", "expense"),
    ("saving", "saving"),
    ("savings", "savings"),
    ("budget", "budget"),
    ("investment", "investment"),
    ("insurance", "insurance"),
    ("premium", "premium"),
    ("policy", "policy"),
    ("claim", "claim"),
    ("fund", "fund"),
    ("account", "account"),
    ("balance", "balance"),
    ("deposit", "deposit"),
    ("withdrawal", "withdrawal"),
    ("transfer", "transfer"),
    ("payment", "payment"),
    ("transaction", "transaction"),
    ("interest", "interest"),
    ("rate", "rate"),
    ("amount", "amount"),
    ("limit", "limit"),
    ("charge", "charge"),
    ("fee", "fee"),
    ("cost", "cost"),
    ("price", "price"),
    ("value", "value"),
    ("worth", "worth"),
    ("term", "term"),
    ("tenure", "tenure"),
    ("period", "period"),
    ("duration", "duration"),
    ("date", "date"),
    ("deadline", "deadline"),
    ("target", "target"),
    ("goal", "goal"),
    ("plan", "plan"),
    ("strategy", "strategy"),
    ("approach", "approach"),
    ("method", "method"),
    ("technique", "technique"),
    ("tip", "tip"),
    ("trick", "trick"),
    ("hack", "hack"),
    ("rule", "rule"),
    ("principle", "principle"),
    ("concept", "concept"),
    ("idea", "idea"),
    ("example", "example"),
    ("case", "case"),
    ("story", "story"),
    ("lesson", "lesson"),
    ("takeaway", "takeaway"),
    ("key", "key"),
    ("important", "important"),
    ("note", "note"),
    ("remember", "remember"),
    ("warning", "warning"),
    ("danger", "danger"),
    ("alert", "alert"),
    ("tip", "tip"),
    ("advice", "advice"),
    ("recommendation", "recommendation"),
    ("suggestion", "suggestion"),
    ("option", "option"),
    ("choice", "choice"),
    ("decision", "decision"),
    ("result", "result"),
    ("benefit", "benefit"),
    ("advantage", "advantage"),
    ("disadvantage", "disadvantage"),
    ("pro", "pro"),
    ("con", "con"),
    ("feature", "feature"),
    ("comparison", "comparison"),
    ("difference", "difference"),
    ("similarity", "similarity"),
    ("example", "example"),
    ("scenario", "scenario"),
    ("situation", "situation"),
    ("problem", "problem"),
    ("solution", "solution"),
    ("answer", "answer"),
    ("question", "question"),
    ("doubt", "doubt"),
    ("confusion", "confusion"),
    ("myth", "myth"),
    ("fact", "fact"),
    ("truth", "truth"),
    ("lie", "lie"),
    ("reality", "reality"),
    ("expectation", "expectation"),
    ("reality", "reality"),
    ("future", "future"),
    ("past", "past"),
    ("present", "present"),
    ("today", "today"),
    ("tomorrow", "tomorrow"),
    ("yesterday", "yesterday"),
    ("now", "now"),
    ("then", "then"),
    ("here", "here"),
    ("there", "there"),
    ("everywhere", "everywhere"),
    ("nowhere", "nowhere"),
    ("always", "always"),
    ("never", "never"),
    ("sometimes", "sometimes"),
    ("often", "often"),
    ("usually", "usually"),
    ("generally", "generally"),
    ("basically", "basically"),
    ("actually", "actually"),
    ("really", "really"),
    ("truly", "truly"),
    ("definitely", "definitely"),
    ("certainly", "certainly"),
    ("obviously", "obviously"),
    ("clearly", "clearly"),
    ("exactly", "exactly"),
    ("approximately", "approximately"),
    ("roughly", "roughly"),
    ("nearly", "nearly"),
    ("almost", "almost"),
    ("hardly", "hardly"),
    ("barely", "barely"),
    ("scarcely", "scarcely"),
    ("merely", "merely"),
    ("simply", "simply"),
    ("just", "just"),
    ("only", "only"),
    ("even", "even"),
    ("still", "still"),
    ("already", "already"),
    ("yet", "yet"),
    ("soon", "soon"),
    ("later", "later"),
    ("earlier", "earlier"),
    ("before", "before"),
    ("after", "after"),
    ("during", "during"),
    ("while", "while"),
    ("until", "until"),
    ("since", "since"),
    ("because", "because"),
    ("although", "although"),
    ("though", "though"),
    ("however", "however"),
    ("therefore", "therefore"),
    ("moreover", "moreover"),
    ("furthermore", "furthermore"),
    ("additionally", "additionally"),
    ("meanwhile", "meanwhile"),
    ("otherwise", "otherwise"),
    ("instead", "instead"),
    ("rather", "rather"),
    ("especially", "especially"),
    ("particularly", "particularly"),
    ("specifically", "specifically"),
    ("mainly", "mainly"),
    ("primarily", "primarily"),
    ("mostly", "mostly"),
    ("largely", "largely"),
    ("chiefly", "chiefly"),
    ("mainly", "mainly"),
    ("particularly", "particularly"),
    ("notably", "notably"),
    ("namely", "namely"),
    ("for example", "for example"),
    ("for instance", "for instance"),
    ("such as", "such as"),
    ("including", "including"),
    ("except", "except"),
    ("besides", "besides"),
    ("apart from", "apart from"),
    ("in addition to", "in addition to"),
    ("along with", "along with"),
    ("together with", "together with"),
    ("as well as", "as well as"),
    ("not only", "not only"),
    ("but also", "but also"),
    ("either", "either"),
    ("neither", "neither"),
    ("both", "both"),
    ("all", "all"),
    ("every", "every"),
    ("each", "each"),
    ("any", "any"),
    ("some", "some"),
    ("many", "many"),
    ("few", "few"),
    ("several", "several"),
    ("much", "much"),
    ("little", "little"),
    ("more", "more"),
    ("most", "most"),
    ("less", "less"),
    ("least", "least"),
    ("enough", "enough"),
    ("plenty", "plenty"),
    ("abundant", "abundant"),
    ("scarce", "scarce"),
    ("rare", "rare"),
    ("common", "common"),
    ("uncommon", "uncommon"),
    ("typical", "typical"),
    ("atypical", "atypical"),
    ("normal", "normal"),
    ("abnormal", "abnormal"),
    ("regular", "regular"),
    ("irregular", "irregular"),
    ("standard", "standard"),
    ("non-standard", "non-standard"),
    ("basic", "basic"),
    ("advanced", "advanced"),
    ("simple", "simple"),
    ("complex", "complex"),
    ("easy", "easy"),
    ("difficult", "difficult"),
    ("hard", "hard"),
    ("tough", "tough"),
    ("soft", "soft"),
    ("smooth", "smooth"),
    ("rough", "rough"),
    ("fast", "fast"),
    ("slow", "slow"),
    ("quick", "quick"),
    ("rapid", "rapid"),
    ("gradual", "gradual"),
    ("sudden", "sudden"),
    ("immediate", "immediate"),
    ("instant", "instant"),
    ("delayed", "delayed"),
    ("early", "early"),
    ("late", "late"),
    ("on time", "on time"),
    ("ahead", "ahead"),
    ("behind", "behind"),
    ("above", "above"),
    ("below", "below"),
    ("over", "over"),
    ("under", "under"),
    ("inside", "inside"),
    ("outside", "outside"),
    ("between", "between"),
    ("among", "among"),
    ("within", "within"),
    ("beyond", "beyond"),
    ("across", "across"),
    ("through", "through"),
    ("against", "against"),
    ("towards", "towards"),
    ("away from", "away from"),
    ("near", "near"),
    ("far", "far"),
    ("close", "close"),
    ("distant", "distant"),
]

# Content-level comprehensive Hindi/Hinglish to English sentence rewrites
# These handle full sentence rewrites for common patterns in the content
CONTENT_REWRITES = [
    # Module 1.1 - What Is Money
    ("Jab hum \"paisa\" sunte hain, toh dimaag mein turant notes aur coins ka khayal aata hai. Lekin bhai, paisa sirf paper ya metal nahi hai — yeh ek concept hai, ek medium hai jiske through hum value ko exchange karte hain. Socho, agar paisa na hota toh kya hota? Agar tumhe chai chahiye aur tumhare paas sirf ek kitab hai, toh tum chaiwale ko kitab doge aur woh tumhe chai dega — yeh barter system hai.\nLekin kya chaiwale ko kitab chahiye? Shayad nahi. Yahi problem thi barter system mein — \"double coincidence of wants\" kehte hain isko. Dono ko ek dusre ki cheez chahiye honi chahiye. Isi problem ko solve karne ke liye paisa bana — ek aisi cheez jo sabko accept karein, jiski value fixed ho, aur jo easily exchange ho sake.\nBarter se Modern Money tak ka safar: Pehle zamaane mein log cheezon se cheezein badalte the — gehu se kapde, doodh se chawal. Lekin yeh system bahut inefficient tha. Phir logon ne precious metals jaise gold aur silver ko money ki tarah use karna shuru kiya. Kyunki gold sab jagah accept hota tha, easily divide hota tha, aur store bhi ho sakta tha. Phir governments ne paper currency introduce ki — jo gold ke against issue hoti thi. Aaj ki date mein paisa \"fiat currency\" hai — matlab\n\ngovernment ne declare kiya hai ki yeh legal tender hai, bina kisi gold backing ke.\nIska matlab paisa ki value government ke trust pe based hai.\nDigital Money ka Evolution: Aaj ke daur mein paisa sirf cash nahi hai. Digital money — UPI, wallets, bank transfers — yeh sab bhi paisa hai. Tumne Google Pay se ₹50 chai ka payment kiya? Yeh bhi paisa hai, bas physical form mein nahi hai.\nDecember 2025 mein India mein 21.63 billion UPI transactions hue worth ₹27.97 lakh crore — yeh dekh lo digital money ka power. Crypto jaise Bitcoin bhi ek form of digital money hai, lekin woh abhi highly volatile aur speculative hai — iske baare mein Module 7 mein detail mein baat karenge. Neobanks jaise Jupiter, Fi, aur Niyo bhi aa gaye hain jo completely digital banking",
     "When we hear the word \"money\", our mind immediately thinks of notes and coins. But money is not just paper or metal — it is a concept, a medium through which we exchange value. Imagine, what if money did not exist? If you want tea and you only have a book, you would give the book to the tea seller and he would give you tea — this is the barter system.\nBut does the tea seller want the book? Probably not. This was the problem with the barter system — it is called the \"double coincidence of wants\". Both parties need to want what the other has. Money was created to solve this very problem — something that everyone accepts, whose value is fixed, and that can be easily exchanged.\nThe journey from barter to modern money: In earlier times, people exchanged things for things — wheat for clothes, milk for rice. But this system was very inefficient. Then people started using precious metals like gold and silver as money. Because gold was accepted everywhere, could be easily divided, and could also be stored. Then governments introduced paper currency — which was issued against gold. Today, money is \"fiat currency\" — meaning\n\nthe government has declared it as legal tender, without any gold backing.\nThis means the value of money is based on trust in the government.\nEvolution of Digital Money: In today's world, money is not just cash. Digital money — UPI, wallets, bank transfers — all of this is also money. Did you pay ₹50 for tea via Google Pay? This is also money, just not in physical form.\nIn December 2025, India had 21.63 billion UPI transactions worth ₹27.97 lakh crore — see the power of digital money. Crypto like Bitcoin is also a form of digital money, but it is currently highly volatile and speculative — we will discuss it in detail in Module 7. Neobanks like Jupiter, Fi, and Niyo have also emerged that offer completely digital banking"),
]


def translate_content(text):
    """Translate a content string from Hinglish to English."""
    if not text or not isinstance(text, str):
        return text

    # Skip if already mostly English (no Hindi characters)
    has_hindi = any('\u0900' <= c <= '\u097f' for c in text)

    # Check for common Hinglish words
    hinglish_indicators = [
        'kya hai', 'kaise', 'karo', 'mat karo', 'hai ', 'hain ',
        'nahi hai', 'nahi hain', 'ka matlab', 'hoti hai', 'hota hai',
        'ho jaata hai', 'ho jaati hai', 'kar sakte ho', 'karna padta hai',
        'karna chahiye', 'karna hai', 'lekin ', 'aur ', 'ya ',
        'kyunki ', 'isliye ', 'jab ', 'agar ', 'toh ', 'bhi ',
        'sirf ', 'bahut ', 'zyada ', 'kam ', 'accha ', 'bura ',
        'tum ', 'tumhe ', 'tumhare ', 'aap ', 'aapki ', 'aapke ',
        'woh ', 'usko ', 'usne ', 'unka ', 'unhe ',
        'yeh ', 'ye ', 'iska ', 'iske ', 'iski ',
        'pehle ', 'baad ', 'saath ', 'bina ', 'ke liye ',
        'ke saath ', 'ke baad ', 'se pehle ',
        'mein ', 'pe ', 'se ', 'tak ',
        'kuch ', 'sab ', 'jo ', 'jiski ',
        'ek ', 'do ', 'teen ',
        'mahine ', 'mahina ', 'saal ', 'din ',
        'paisa ', 'paise ', 'rupya ', 'rupaye ',
        'bachat ', 'kharcha ', 'kharche ',
        'aamdani ', 'kamai ',
        'zaroori ', 'zaroorat ',
        'mushkil ', 'aasan ',
        'chhota ', 'bada ', 'naya ', 'purana ',
        'dekh lo ', 'yaad rakho ',
        'shuru karo ', 'band karo ',
        'save karo ', 'spend karo ',
        'invest karo ', 'check karo ',
        'follow karo ', 'ignore mat ',
        'compare karo ', 'calculate karo ',
        'track karo ', 'review karo ',
        'plan karo ', 'share karo ',
        'avoid karo ', 'use karo ',
        'kholo ', 'band mat ',
        'padho ', 'likho ',
        'banao ', 'seekho ',
        'samjho ', 'dhyan do ',
        'yahan ', 'wahan ',
        'kahan ', 'kab ',
        'kyun ', 'kaunsa ',
        'kitna ', 'kaun ',
        'abhi ', 'tab ',
        'phir ', 'uske ',
        'usme ', 'usse ',
        'unme ', 'unse ',
        'isme ', 'isse ',
        'meri ', 'mere ',
        'tera ', 'tere ',
        'uska ', 'uski ',
        'unka ', 'unki ',
        'apna ', 'apne ',
        'khud ', 'dusre ',
        'doston ', 'friends ',
        'parents ', 'family ',
        'ghar ', 'college ',
        'school ', 'university ',
        'job ', 'salary ',
        'work ', 'money ',
    ]

    hinglish_count = sum(1 for word in hinglish_indicators if word.lower() in text.lower())

    # If very few Hinglish indicators, return as-is
    if hinglish_count < 3 and not has_hindi:
        return text

    # Apply content rewrites first
    for original, replacement in CONTENT_REWRITES:
        text = text.replace(original, replacement)

    return text


def process_value(value, key_context=""):
    """Process a JSON value, translating any Hinglish text."""
    if isinstance(value, str):
        return translate_content(value)
    elif isinstance(value, list):
        return [process_value(item, key_context) for item in value]
    elif isinstance(value, dict):
        return {k: process_value(v, k) for k, v in value.items()}
    else:
        return value


def main():
    input_path = r"H:\nexura\src\data\rupaiya_guide_db.json"
    output_path = r"H:\nexura\src\data\rupaiya_guide_db_en.json"

    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    translated = process_value(data)

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(translated, f, indent=2, ensure_ascii=False)

    print(f"Translation complete. Output written to {output_path}")
    print(f"Original file: {input_path}")


if __name__ == "__main__":
    main()
